name: PlayerSpawn
version: '${project.version}'
main: me.firedragon5.playerspawn.PlayerSpawn
api-version: 1.19


commands:
    setspawn:

    spawn:


    sethome:


    home:


    homehelp:


    delhome:


    setwarp:


    homelist:

    warp:

    spawnmenu:
